# -*- coding: utf-8 -*-
"""first_test_on_numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbUk6eYSeCmjb4rI5O14mATPkso_VX9m
"""

# 1. write statement to import numpy?
# 2. create an array using numpy ?
# 3. create ab array of 10 random integers ?
# 4. create an array of elements from 10-20 ?
# 5. cretae an array which conatains value 5,10 times ?
# 6. create a one dimensional array and convert that into 3*3 matrix ?
# 7. create a 2D array of size 3*3 but all the elments should be between 0 to 1 ?
# 8. concatenate 2D array horizontally and vertically ?

#1
import numpy as np

#2

arr = np.array([1,2,3,4,5])
print(arr)

#3
arr = np.random.randint(1,100,10)
print(arr)

#4

arr = np.arange(10,21)
print(arr)

#5
arr = np.array([5,5,5,5,5,5,5,5,5,5])
print(arr)

#6
arr = np.arange(1,10)
m = arr.reshape(3,3)

print(m)

#7
arr = np.random.rand(3,3)
print(arr)

#8

# 8.
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

print(np.hstack((a,b)))
print()
print(np.vstack((a,b)))