# -*- coding: utf-8 -*-
"""numpy_methods_day_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3fpRw3DtPCI3_5FKDzAonh9p7_W56Co
"""

import numpy as np

#### Operations on Array

a = np.arange(1,5).reshape(2,2)
a

b = np.arange(5,9).reshape(2,2)
b

a+b ##1+5=6 , 2+6=8, 3+7=10 , 4+8=12

a-b

## for matrix Multiplication
a.dot(b)

a = np.arange(1,5)
a

a**2

a**3

np.sqrt(a)

np.sin(a)

np.cos(a)

# LinSpace() ----> It will return same gap values in a given range .

a = np.linspace(1,2,5)
a

# Unique() ----> It will return 3 arrays .
# arr ---> return original values of array .
# return_index = True ----> return return index value of unqie numbers .
# return_counts = True ----> It will return total freqnecy of each unique value .

a = np.array([1,2,3,2,2,2,3,3,2,4,5])
a

np.unique(a , return_index=True , return_counts=True)

# hstack() and vstack()

# hstack() ----> It will add 2 or more arrays in horizontally .
# vstack() ----> It will add 2 or more arrays in vertically.

a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)

np.hstack((a,b,c))

np.vstack((a,b,c))

# array (30,80) total elements 36 ---> reshape (2*18, 4*9,6*6)

# array ----> [6,10], [11,15] ---> conbined horizontally