# -*- coding: utf-8 -*-
"""numpy_methods_day1&2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gM-1GqFuBC-nG1yKtNavUfAK-QOIPZpf
"""

import numpy as np

a = [1,2,3,4,5]
b = np.array(a)
b

a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

print("Total ROws and columns:" , b.shape)
print("Total Elements:" , b.size)
print("Total Dimension:" , b.ndim)

# Pre-defined Functions in Numpy

# (1). zeros() ----> It will create an array in which all the values are 0 .
a = np.zeros(4)
a

a = np.zeros((2,3))
a

# (2). ones() ---> It will create an array in which all the values are 1 .
a = np.ones(4)
a

a = np.ones((3,4))
a

# (3). eye() ----> It will create an array in which digonal positional elements are 1 and rest all
# are 0.

a = np.eye(4)
a

# (4). diag() ----> It will set our custm values on digonal position .
a = np.array([1,45,78,90])
a

b = np.diag(a)
b

# (5). Random Module
# (a). Randint() ---> It will create random numbers in a given range .
# sytax: np.random.randint(min_range , max_range , total_numbers)

a = np.random.randint(1,10,3)
a

# (b). Rand() ---> It will create random numbers in range 0-1/

a = np.random.rand(5)
a

# (c). seed() ----> It will fix our random generated data .

np.random.seed(3)
a = np.random.randint(1,10,3)
a

# View Vs Copy

# View means modification in original data and copy means changes in duplicate data will not reflect
# the original data .

a = np.array([10,20,30,40,50,60,70,80])
a

a[3:6] = 0

a

a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
b

a

# Operation on Array

# (1). arange() -----> It will works as as for loop in numpy .

a = np.arange(1,16,1)
a

a>10

b = a>10
a[b]

b = a%2== 0

a[b]

# Reshaping condition
# n(rows) * n(columns) = n(total_elements)

# total ememtns = 12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3

a = np.random.randint(1,50,12)
a

a.reshape(2,6)

a.reshape(3,4)

# a.reshape(3,5)

a = np.arange(1,5).reshape(2,2)
a

b = np.arange(5,9).reshape(2,2)
b

a+b

a-b

a*b   ### Not matrix multiplication

a.dot(b)   ### Matrix multiplication

a

b

